config/routes.rb
FoodFinder::Application.routes.draw do
  devise_for :users

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/all_events"

  get "events/nearby"

  resources :rsvps

  resources :events

  resources :users

  root :to => 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/feed', to: 'static_pages#all_events'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  validates :name, :presence => true
  validates :name, :uniqueness => true
  validates :email, :presence => true
  validates :email, :uniqueness => true
  # attr_accessible :title, :body
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page], :per_page => 10, :order => 'id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    @user_events = Event.where("user_id =" + @user.id.to_s)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    if (not user_signed_in? ) or (not current_user.id == @user.id)
      redirect_to root_path, notice: "You must sign in as this user to edit their profile."
    else
      @user = User.find(params[:id])
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
        flash[:success] = "Welcome to Food Finder!"
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if (not user_signed_in? ) or (not current_user.id == @user.id)
      redirect_to root_path, notice: "You must sign in as this user to edit their profile."
    else

      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    if (not user_signed_in? ) or (not current_user.id == @user.id)
      redirect_to root_path, notice: "You must sign in as this user to edit their profile."
    else
      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar", style:"height:#{size}px; width:#{size}px;")
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit 'Sign Up', :class => "btn btn-primary large"%>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%	 provide(:title, "All Users") %>
<h1>Listing users</h1>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
      <li>
        <%= gravatar_for user, 52 %>
        <%= link_to user.name, user %>
      </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1 xmlns="http://www.w3.org/1999/html">
  <%= gravatar_for(@user, 100) %>
  <%= @user.name %>
</h1>
<p id="notice"><%= notice %></p>
<div class="butts">
  <% if @user_events.length > 0 %>
      <h3 STYLE="text-align: center;"><%= @user.name %>'s Events </h3>
      <ol class="events">
        <% @user_events.each do |evt| %>
            <li>
              <a href="/events/<%=   evt.id %>"><span class="user_event_content"> <%= evt.name %> </span> </a>
              </br>
             <i> <%= evt.description %>   </i>
            </li>
        <% end %>
      </ol>
  <% end %>
</div>