config/routes.rb
FoodFinder::Application.routes.draw do
  devise_for :users

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/all_events"

  get "events/nearby"

  resources :rsvps

  resources :events

  resources :users

  root :to => 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/feed', to: 'static_pages#all_events'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :contact, :description, :latitude, :location, :longitude, :menu, :time, :user_id
  validates :name, :contact, :location, :time, :user_id , :presence=> true

  default_scope order: 'events.created_at DESC'
end

app/controllers/events_controller.rb
require 'net/http'

class EventsController < ApplicationController
  before_filter :correct_user, only: :destroy
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.json { render json: @events }
    end
  end

  # GET /events/nearby
  def nearby
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end



  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    if user_signed_in?
      @event = Event.new(params[:event])
      @event.user_id = current_user.id

      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render json: @event, status: :created, location: @event }
        else
          format.html { render action: "new" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    else
         redirect_to new_user_session_path, notice: "You must sign in before creating an event."
    end
   end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    if (not user_signed_in? ) or (not current_user.id == @event.user_id)
      redirect_to root_path, notice: "You must sign in as this user to update their event."
    else
      respond_to do |format|
        if @event.update_attributes(params[:event])
          @greeting = "Hello"
          @new_time = @event.time.to_s
          @name = @event.name
          @all_rsvps = Rsvp.where("event_id = ?", @event.id)
          if(@all_rsvps.length > 0)
            @all_rsvps.each do |rsvp|
              @user = User.where("id = ?", rsvp.user_id).first
              s = "sendgrid.com/api/mail.send.json?to=sibnerian%40gmail.com&from=sibnerian%40gmail.com&subject=Hello%20Ian%20Sibner.Your%20event%20is%20now%March%20thirtieth%20twwentyfifteen&text=sentfromsendgrid&api_user=app14249328%40heroku.com&api_key=5lvtybk3"
              s = URI::escape(s)
              uri = URI(s)
              request = Net::HTTP::Get.new(uri.path)

              response = Net::HTTP.new(uri.host,uri.port) do |http|
                http.request(request)
              end

              puts response
            end
          end

          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    if (not user_signed_in? ) or (not current_user.id == @event.user_id)
      redirect_to root_path, notice: "You must sign in as this user to update their event."
    else
      @event.destroy


      respond_to do |format|
        format.html { redirect_to root_url, notice: @event.name + " cancelled." }
        format.json { head :no_content }
      end
    end
  end



  def create_rsvp
    @event = Event.find(params[:id])
  if not user_signed_in?
    redirect_to new_user_session_path, notice: "You must sign in to RSVP"
  end

    active_rsvp = Rsvp.new
    active_rsvp.event_id = @event.id
    active_rsvp.user_id = current_user.id
    active_rsvp.save
    redirect_to @event, "You have successfully RSVP'd to " + @event.name
  end

  def delete_rsvp
    @event = Event.find(params[:id])
    if not user_signed_in?
      redirect_to new_user_session_path, notice: "You must sign in to un-RSVP"
    end

    active_rsvp = Rsvp.where("event_id = ? AND user_id = ?", @event.id, current_user.id).first
    active_rsvp.destroy
    redirect_to root_url, notice: "Successfully un-RSVP'd to" + @event.name



  end

  private

    def correct_user
      @event = Event.find_by_id(params[:id])
      if not user_signed_in?
        redirect_to new_user_session_path, notice: "You must sign in, come on."
      end


      if @event.user_id = current_user.id
      if @event.nil?
        redirect_to root_url , notice: "You can't destroy that event"
      end
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<% provide(:title, 'Edit Event') %>


<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% provide(:title, 'All Events') %>


<h1>Listing events</h1>

<table>
  <tr>
    <th>Contact</th>
    <th>Latitude</th>
    <th>Location</th>
    <th>Longitude</th>
    <th>Menu</th>
    <th>Description</th>
    <th>Time</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.contact %></td>
    <td><%= event.latitude %></td>
    <td><%= event.location %></td>
    <td><%= event.longitude %></td>
    <td><%= event.menu %></td>
    <td><%= event.description %></td>
    <td><%= event.time %></td>
    <td><%= event.user_id %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/nearby.erb
<% provide(:title, "Events Near You") %>

<p id="notice"><%= notice %></p>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgh3w_nXd2jjakw-oftQ3Ze3MWT5zxem4&sensor=true">
</script>
<script type="text/javascript">
    var script = '<script type="text/javascript" src="http://google-maps-' +
            'utility-library-v3.googlecode.com/svn/trunk/infobubble/src/infobubble';
    if (document.location.search.indexOf('compiled') !== -1) {
        script += '-compiled';
    }
    script += '.js"><' + '/script>';
    document.write(script);
</script>

<style>

    #map-canvas {
        height:600px;
        width: 100%;
        margin-left:0;
    }

    #map-canvas img {
        max-width: none;
    }

    #map-canvas label {
        width: auto; display:inline;
    }
    input {
        border: 1px solid  rgba(0, 0, 0, 0.5);
    }
    input.notfound {
        border: 2px solid  rgba(255, 0, 0, 0.4);
    }
</style>

<script type="text/javascript">
    var makeAMap = function() {


        var mapOptions = {
            //center: new google.maps.LatLng(39.9522, -75.1642),
            zoom: 15,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        var map = new google.maps.Map(document.getElementById('map-canvas'),
                mapOptions);


        var image_url = "http://i.imgur.com/22ese9F.png?1";
        var imageIcon = new google.maps.MarkerImage(
                image_url,
                null, /* size is determined at runtime */
                null, /* origin is 0,0 */
                null, /* anchor is bottom center of the scaled image */
                new google.maps.Size(40, 40)
        );


        function createMarker(lat, lng, location){
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(lat, lng),
                map: map,
                animation: google.maps.Animation.DROP,
                icon: imageIcon
            });
            var infowindow = new InfoBubble({
                content: location,
                maxWidth: 200,
                disableAutoPan: true
            });
            infowindow.hideCloseButton();
            var x = 1;
            google.maps.event.addListener(marker, 'click', function() {
                if(x==1){
                    infowindow.open(map,marker);
                    x=0;
                }
                else{
                    infowindow.close();
                    x=1;
                }
            });
        }

        <% @events.each do |event| %>
        try{
            createMarker(<%= event.latitude or 'null' %>, <%= event.longitude or 'null' %>, "<a href='/events/<%= event.id %>'><%= event.name %> </a>");
        }
        catch(err){
            console.log(err);
        }
        <% end %>


        if(navigator.geolocation){
            navigator.geolocation.getCurrentPosition(function(position) {
                var geolocate = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                var mark = new google.maps.Marker({
                    position: geolocate,
                    map: map
                });
                map.setCenter(geolocate);

                $("#centerBtn").click(function(){
                    var geolocate = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                    var mark = new google.maps.Marker({
                        position: geolocate,
                        map: map
                    });
                    map.setCenter(geolocate);
                });

            });

        }
        else{
            alert("Geolocation is not available. Sorry! ='(")
        }

    };
    $('document').ready(function(){
        makeAMap();
    })
    //google.maps.event.addDomListener(window, 'load', makeAMap);

</script>



  <div id="map-canvas">

  </div>

  <div id="centerBtn" class ="btn btn-primary large">Re-Center</div>

app/views/events/new.html.erb
<% provide(:title, 'New Event') %>


<h1>New event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>


<p id="notice"><%= notice %></p>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgh3w_nXd2jjakw-oftQ3Ze3MWT5zxem4&sensor=true">
</script>
<script type="text/javascript">
    var script = '<script type="text/javascript" src="http://google-maps-' +
            'utility-library-v3.googlecode.com/svn/trunk/infobubble/src/infobubble';
    if (document.location.search.indexOf('compiled') !== -1) {
        script += '-compiled';
    }
    script += '.js"><' + '/script>';
    document.write(script);
</script>
<script>
  $("document").ready(function(){
    $("#time").html("<b>Time</b>: " + moment($("#time").text()).format("dddd, MMMM Do YYYY, h:mm A"))

  });

</script>
<style>

    #map-canvas-event {
        height: 500px;
        width: 500px;
    }

    #map-canvas-event img {
        max-width: none;
    }

    #map-canvas-event label {
        width: auto; display:inline;
    }
    input {
        border: 1px solid  rgba(0, 0, 0, 0.5);
    }
    input.notfound {
        border: 2px solid  rgba(255, 0, 0, 0.4);
    }
</style>

<script type="text/javascript">
    var food_location = new google.maps.LatLng(<%= @event.latitude %>, <%= @event.longitude %>);
    var makeAMap = function() {
        var options = {
            center: food_location,
            zoom: 17,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map2 = new google.maps.Map(document.getElementById("map-canvas-event"),
                options);

        var image_url = "http://i.imgur.com/22ese9F.png?1";
        var imageIcon = new google.maps.MarkerImage(
                image_url,
                null, /* size is determined at runtime */
                null, /* origin is 0,0 */
                null, /* anchor is bottom center of the scaled image */
                new google.maps.Size(40, 40)
        );
        var marker = new google.maps.Marker({
            position: food_location,
            map: map2,
            animation: google.maps.Animation.DROP,
            icon: imageIcon
        });
        var infowindow = new InfoBubble({
            content: "<%= @event.location %>",
            maxWidth: 200
        });
        var x = 1;
        google.maps.event.addListener(marker, 'click', function() {
            if(x==1){
            infowindow.open(map2,marker);
            x=0;
            }
            else{
                infowindow.close();
                x=1;
            }
        });
            /*
        geocoder = new google.maps.Geocoder();
        geocoder.geocode({'latLng': food_location}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                if (results[0]) {
                    infowindow.setContent(results[0].formatted_address);
                }
                else{
                }
            } else {
                alert("Geocoder failed due to: " + status);
            }
        });   */

    };
    google.maps.event.addDomListener(window, 'load', makeAMap);

</script>





<div style="margin-left: 25%">

<p>
  <b>Contact:</b>
  <%= @event.contact %>
</p>

<p style = "display: none;">
  <b>Latitude:</b>
  <%= @event.latitude %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>


<div id="map-canvas-event">

</div>

<p style = "display: none;">
  <b>Longitude:</b>
  <%= @event.longitude %>
</p>

<p>
  <b>Menu:</b>
  <%= @event.menu %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p id="time">
  <b>Time:</b>
  <%= @event.time %>
</p>

</div>

<%  if user_signed_in? and @event.user_id == current_user.id %>
<%= link_to 'Edit', edit_event_path(@event) %> |
    <%= link_to 'Cancel Event', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


<%  if user_signed_in? and Rsvp.where("event_id = ? AND user_id = ?", @event.id, current_user.id).length > 0 %>
    | <%= link_to 'Un-RSVP', Rsvp.where("event_id = ? AND user_id = ?", @event.id, current_user.id).first, method: :delete, data: { confirm: 'Are you sure?' } %>
<%	 else  %>
    <% if user_signed_in? %>
    <form accept-charset="UTF-8" action="/rsvps" class="new_rsvp" id="new_rsvp" method="post"><div style="margin:0;padding:0;display:inline">
      <input name="utf8" type="hidden" value="&#x2713;" />
      <input name="authenticity_token" type="hidden" value="QF/J31xI5Zq9Be4iRfmU+kFf8auytMS6trhMrE/QZ40=" /></div>

      <div class="field" style="display: none;">
        <label for="rsvp_user_id">User</label><br />
        <input id="rsvp_user_id" name="rsvp[user_id]" type="number" value="<%= current_user.id.to_s %>"/>
      </div>
      <div class="field" style="display: none;">
        <label for="rsvp_event_id">Event</label><br />
        <input id="rsvp_event_id" name="rsvp[event_id]" type="number" value="<%= @event.id.to_s %>"/>
      </div>
      <div>
        <input name="commit" type="submit" value="Rsvp" class="btn btn-primary " />
      </div>
      <% end %>

    </div>

    
    </form>
<% end %>