config/routes.rb
FoodFinder::Application.routes.draw do
  devise_for :users

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/all_events"

  get "events/nearby"

  resources :rsvps

  resources :events

  resources :users

  root :to => 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/feed', to: 'static_pages#all_events'

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  attr_accessible :event_id, :user_id
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  # GET /rsvps
  # GET /rsvps.json
  before_filter :authenticate_user!
  def index
    redirect_to root_path, notice: "RSVP created successfully."

  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
    redirect_to root_path, notice: "RSVP created successfully."

  end

  # GET /rsvps/new
  # GET /rsvps/new.json
  def new
    redirect_to root_path, notice: "RSVP created successfully."

  end

  # GET /rsvps/1/edit
  def edit
    redirect_to root_path
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(params[:rsvp])
    #puts "RSVP ######################"
    #puts @rsvp.user_id.to_s
    #puts current_user.id.to_s
    if(not @rsvp.user_id == current_user.id)
      redirect_to "/events/"+ @rsvp.event_id.to_s , notice: "Don't try signing in for the wrong user."
    end
    else
      respond_to do |format|
        if @rsvp.save
          format.html { redirect_to "/events/" + @rsvp.event_id.to_s, notice: 'Rsvp was successfully created.' }
          format.json { render json: @rsvp, status: :created, location: @rsvp }
        else
          format.html { render action: "new" }
          format.json { render json: @rsvp.errors, status: :unprocessable_entity }
        end
      end
  end

  # PUT /rsvps/1
  # PUT /rsvps/1.json
  def update

    redirect_to root_path

  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp = Rsvp.find(params[:id])
    @rsvp.destroy

    respond_to do |format|
      format.html { redirect_to "/events/" + @rsvp.event_id.to_s, notice: "RSVP cancelled." }
      format.json { head :no_content }
    end
  end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsvps/edit.html.erb
<h1>Not Found</h1>

app/views/rsvps/index.html.erb
<h1>Listing rsvps</h1>

<table>
  <tr>
    <th>User</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rsvps.each do |rsvp| %>
  <tr>
    <td><%= rsvp.user_id %></td>
    <td><%= rsvp.event_id %></td>
    <td><%= link_to 'Show', rsvp %></td>
    <td><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
    <td><%= link_to 'Destroy', rsvp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rsvp', new_rsvp_path %>

app/views/rsvps/new.html.erb
<h1>New rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rsvp.user_id %>
</p>

<p>
  <b>Event:</b>
  <%= @rsvp.event_id %>
</p>