config/routes.rb
FoodFinder::Application.routes.draw do
  devise_for :users

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/all_events"

  get "events/nearby"

  resources :rsvps

  resources :events

  resources :users

  root :to => 'static_pages#home'
  match '/about',   to: 'static_pages#about'
  match '/feed', to: 'static_pages#all_events'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By <a href="http://www.isibner.me">Ian Sibner</a>
    and <a href="http://de.linkedin.com/pub/benedikt-lotter/39/941/48b/">Benedikt Lotter</a>.
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Feed Me Maybe", root_path , class: "brand" %>
      <nav>
        <ul class="nav pull-right">

          <li>
            <%= link_to "Home",    root_path %>
          </li>

          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Events <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Near You", events_nearby_path %></li>
              <li><%=  link_to("Feed", feed_path) %></li>
            </ul>
          </li>


          <li>
            <%= link_to "About",    about_path %>
          </li>

          <% if user_signed_in? %>
              <!--
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                </ul>
              </li>
              -->
              <li>
                <%= link_to("New Event", new_event_path) %>
              </li>
              <li>
                 <%= link_to("Profile", current_user) %>
              </li>

              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
          <% else %>
              <li>
                <%= link_to('Login', new_user_session_path)  %>
              </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%=  render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <!-- ****************** TODO ADD BOOTBOX.JS ************** -->
  <% end %>
  <%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>